name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Swift package for iOS
        run: xcodebuild -scheme RorkUsbmux -destination 'generic/platform=iOS' -derivedDataPath DerivedData build
